---
name: "pre-release"

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    runs-on: "ubuntu-latest"
    env:
      TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"
        with:
          lfs: true
          fetch-depth: 0
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ADMIN_GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            bin/jftv-win.exe
            bin/jftv-linux
            bin/jftv-macos
        id: "automatic_releases"
