---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ADMIN_GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Linux Executable (Dev)"
          files: |
            ./bin/jftv-linux
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ADMIN_GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "MacOS Executable (Dev)"
          files: |
            ./bin/jftv-macos
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ADMIN_GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Windows Executable (Dev)"
          files: |
            ./bin/jftv-win.exe
